package control.message;

public enum LoginMenuMessage {
    USER_CREATED,
    USERNAME_EXISTS,
    NICKNAME_EXISTS,
    LOGGED_IN,
    NO_MATCH,
    USERNAME_CONTAIN_SPACE,
    NICKNAME_CONTAIN_SPACE,
    PASSWORD_CONTAIN_SPACE,
    ERROR
}
