package control.message;

public enum ProfileMenuMessage {
    NICKNAME_CHANGED,
    NICKNAME_CONTAIN_WHITESPACE,
    NICKNAME_EXISTS,
    PASSWORD_CHANGED,
    INVALID_CURRENT_PASSWORD,
    PASSWORD_CONTAIN_WHITESPACE,
    SAME_NEW_AND_CURRENT_PASSWORD,
    ERROR
}
